apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp
spec:
  project: default
  source:
    repoURL: git@github.com:yotam-halperin/argocd-crm5-charts.git
    targetRevision: HEAD
    path: infra-apps
  destination:
    server: https://kubernetes.default.svc
