apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:yotam-halperin/argocd-crm5-infra.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
