apiVersion: v1
kind: ConfigMap
metadata:
  name: myconf
  namespace: {{ .Values.namespace }}
data:
  LOG_LEVEL: "info"
  MONGODB_URI: "mongodb://{{ .Values.mongodb.auth.rootUser }}:{{ .Values.mongodb.auth.rootPassword }}@{{ .Release.Name }}-mongodb-headless"
