apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crm
  name: crm
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - image: {{ .Values.deployment.containerImage }}
        name: demo-crm
        ports:
        - containerPort: {{ .Values.deployment.appContainerPort }}
          protocol: TCP
        env:
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: LOG_LEVEL
        - name: PERSISTENCE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PERSISTENCE
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: myconf
              key: MONGODB_URI
        resources:
{{  toYaml .Values.resources | indent 10 }}
