{{- if .Values.destroyer.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: destroyer
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: destroyer
            image: docker.io/bitnami/mongodb:6.0.4-debian-11-r0
            imagePullPolicy: IfNotPresent
            command:
            - bash
            - -c
            - mongosh mongodb://{{ .Values.mongodb.auth.rootUser }}:{{ .Values.mongodb.auth.rootPassword }}@{{ .Release.Name }}-mongodb-headless --eval "use test" --eval "db.dropDatabase()"

          restartPolicy: OnFailure
{{- end }}