apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.applicationPort }}
    protocol: TCP
    targetPort: {{ .Values.service.conPort }}
  selector:
    app: crm
  {{ if .Values.tls.enabled }}type: "ClusterIP"{{ else }}type: "LoadBalancer"{{ end }}

